version: '3'
services:
  app:
    container_name: main_app
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_USER: ${user}
      DB_PASSWORD: ${password}
      DB_NAME: ${dbname}
      DB_HOST: ${host}
      DB_PORT: 5432

  db:
    container_name: project_management_db
    image: postgres
    environment:
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${password}
      POSTGRES_DB: ${dbname}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: